# https://golangci-lint.run/usage/configuration/#config-file

run:
  timeout: 2m


linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    # - golint
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace


linters-settings:
  govet:
    disable:
      - printf
